In [24]:
import numpy as np

In [25]:
#membuat data array
sample_data = np.array([[-1.2, 2.2, 0.5],
                        [1.1, 4.2, 3.3],
                        [4.1, -2.1, -3.1],
                        [-3.1, -3.3, 0.5]])
sample_data

array([[-1.2,  2.2,  0.5],
       [ 1.1,  4.2,  3.3],
       [ 4.1, -2.1, -3.1],
       [-3.1, -3.3,  0.5]])

In [26]:
from sklearn import preprocessing

In [27]:
#binarisasi data preprocessing
preprocessor = preprocessing.Binarizer(threshold=(0.5))
binarizer_data = preprocessor.transform(sample_data)
binarizer_data

array([[0., 1., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [28]:
#scaling data preprocessing
preprocessor = preprocessing.MinMaxScaler(feature_range=(0,1))
scale_data = preprocessor.fit_transform(sample_data)
scale_data

array([[0.26388889, 0.73333333, 0.5625    ],
       [0.58333333, 1.        , 1.        ],
       [1.        , 0.16      , 0.        ],
       [0.        , 0.        , 0.5625    ]])

In [29]:
#normalized l1 data preprocessing
normalized_l1 = preprocessing.normalize(sample_data, norm='l1')
normalized_l1

array([[-0.30769231,  0.56410256,  0.12820513],
       [ 0.12790698,  0.48837209,  0.38372093],
       [ 0.44086022, -0.22580645, -0.33333333],
       [-0.44927536, -0.47826087,  0.07246377]])

In [30]:
#normalized l2 data preprocessing
normalized_l2 = preprocessing.normalize(sample_data, norm='l2')
normalized_l2

array([[-0.46959629,  0.86092653,  0.19566512],
       [ 0.20170757,  0.77015619,  0.60512272],
       [ 0.73840919, -0.37820959, -0.55830939],
       [-0.68053841, -0.72444412,  0.10976426]])